/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_0_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_10_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_11_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_12_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_13_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_13_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_14_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_14_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_15_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_19_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_1_FUNC_ALT3 0x03u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_1_MODE_PULL_UP 0x02u
/*!
 * @brief Controls open-drain mode.: Normal. Normal push-pull output */
#define PIO0_1_OD_NORMAL 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_21_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_22_FUNC_ALT7 0x07u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_23_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_23_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_23_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_23_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_25_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_25_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_26_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_27_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_28_FUNC_ALT1 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_28_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_28_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_29_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_29_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_30_FUNC_ALT1 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_30_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_30_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_5_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_5_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_8_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_9_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_0_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_10_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_12_FUNC_ALT2 0x02u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_12_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_13_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_16_FUNC_ALT2 0x02u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_16_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_17_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_17_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_18_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_21_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_21_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_25_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_25_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_2_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_30_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_3_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_4_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_7_FUNC_ALT0 0x00u

/*! @name PIO1_2 (coord G12), LED_SYS_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_SYS_GREEN_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_SYS_GREEN_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_LED_SYS_GREEN_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_SYS_GREEN_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LED_SYS_GREEN_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO1_3 (coord G13), LED_SYS_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_SYS_RED_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_SYS_RED_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
#define BOARD_LED_SYS_RED_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_SYS_RED_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LED_SYS_RED_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_19 (coord E6), LINKA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LINKA_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LINKA_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_LINKA_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_LINKA_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_LINKA_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PIO1_18 (coord G9), KEY_WAKE
  @{ */
#define BOARD_KEY_WAKE_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_KEY_WAKE_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_KEY_WAKE_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO1_10 (coord J7), PWR_3V3A
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PWR_3V3A_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_PWR_3V3A_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define BOARD_PWR_3V3A_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_PWR_3V3A_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_PWR_3V3A_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_25 (coord A11), PWR_5V
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PWR_5V_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_PWR_5V_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_PWR_5V_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_PWR_5V_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_PWR_5V_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PIO1_0 (coord E1), OverRange
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_OverRange_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_OverRange_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_OverRange_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_OverRange_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_OverRange_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO1_30 (coord F9), NFC_IRQ
  @{ */
#define BOARD_NFC_IRQ_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_NFC_IRQ_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_NFC_IRQ_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO0_29 (coord H8), NB_NETSTATUS
  @{ */
#define BOARD_NB_NETSTATUS_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_NB_NETSTATUS_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_NB_NETSTATUS_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_10 (coord F2), ADC_FORMAT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ADC_FORMAT_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_ADC_FORMAT_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define BOARD_ADC_FORMAT_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_FORMAT_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_ADC_FORMAT_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_16 (coord J2), ADC_SYNC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ADC_SYNC_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_ADC_SYNC_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_ADC_SYNC_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_SYNC_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_ADC_SYNC_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_7 (coord G5), ADC_MODE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ADC_MODE_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_ADC_MODE_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_ADC_MODE_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_MODE_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_ADC_MODE_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO0_21 (coord A12), ADC_RDY
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ADC_RDY_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_ADC_RDY_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_ADC_RDY_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_RDY_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_ADC_RDY_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO1_21 (coord M7), PWR_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PWR_SDA_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_PWR_SDA_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_PWR_SDA_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_PWR_SDA_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_PWR_SDA_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO1_7 (coord J5), SensorTest
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SensorTest_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SensorTest_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_SensorTest_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_SensorTest_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_SensorTest_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PIO0_14 (coord C13), TMP_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_TMP_SCL_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_TMP_SCL_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_TMP_SCL_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_TMP_SCL_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_TMP_SCL_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO0_13 (coord C12), TMP_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_TMP_SDA_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_TMP_SDA_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define BOARD_TMP_SDA_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_TMP_SDA_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_TMP_SDA_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO1_13 (coord B3), FLASH_MOSI
  @{ */
#define BOARD_FLASH_MOSI_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_MOSI_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_MOSI_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO1_16 (coord C7), FLASH_MISO
  @{ */
#define BOARD_FLASH_MISO_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_MISO_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_MISO_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO1_12 (coord F12), FLASH_SCK
  @{ */
#define BOARD_FLASH_SCK_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SCK_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SCK_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PIO1_17 (coord J9), FLASH_WP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_FLASH_WP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_FLASH_WP_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_FLASH_WP_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_WP_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_WP_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_30 (coord E5), ADC_MISO
  @{ */
#define BOARD_ADC_MISO_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_MISO_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_ADC_MISO_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO0_28 (coord F13), ADC_SPI_SCK
  @{ */
#define BOARD_ADC_SPI_SCK_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_SPI_SCK_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_ADC_SPI_SCK_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_27 (coord N2), NB_RXD
  @{ */
#define BOARD_NB_RXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_NB_RXD_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_NB_RXD_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PIO0_26 (coord H12), NB_TXD
  @{ */
#define BOARD_NB_TXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_NB_TXD_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_NB_TXD_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PIO0_15 (coord L2), FLASH_CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_FLASH_CS_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_FLASH_CS_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_FLASH_CS_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_CS_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_CS_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO1_4 (coord B2), FLT_CLK
  @{ */
#define BOARD_FLT_CLK_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_FLT_CLK_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_FLT_CLK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PIO0_0 (coord L12), ADC_CLK
  @{ */
#define BOARD_ADC_CLK_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_CLK_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_ADC_CLK_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PIO0_1 (coord F5), SPD_FREQ_CAP
  @{ */
#define BOARD_SPD_FREQ_CAP_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_SPD_FREQ_CAP_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_SPD_FREQ_CAP_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_5 (coord A7), PWR_CAT1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PWR_CAT1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_PWR_CAT1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define BOARD_PWR_CAT1_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_PWR_CAT1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_PWR_CAT1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO1_25 (coord B8), NFC_RSTPD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_NFC_RSTPD_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_NFC_RSTPD_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_NFC_RSTPD_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_NFC_RSTPD_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_NFC_RSTPD_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
