/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_0_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_10_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_11_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO0_12_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_13_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_13_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_14_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_14_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_15_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_17_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_18_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_19_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_1_FUNC_ALT3 0x03u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_1_MODE_PULL_UP 0x02u
/*!
 * @brief Controls open-drain mode.: Normal. Normal push-pull output */
#define PIO0_1_OD_NORMAL 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_20_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_21_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_22_FUNC_ALT7 0x07u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_23_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_23_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_23_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_23_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_24_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_24_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_25_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_26_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_27_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_28_FUNC_ALT1 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_28_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_28_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_29_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_29_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_2_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_30_FUNC_ALT1 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_30_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast-mode, output slew rate is faster.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_30_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_31_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_31_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_31_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_3_FUNC_ALT1 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_4_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_5_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_8_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO0_9_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_0_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_12_FUNC_ALT2 0x02u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_12_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_13_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_14_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_15_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO1_16_FUNC_ALT2 0x02u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_16_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_17_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_17_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_18_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_19_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_19_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_1_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_20_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_20_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_21_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_21_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_25_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_25_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_26_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_26_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_27_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_27_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_28_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_2_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_30_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_30_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_3_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO1_4_FUNC_ALT3 0x03u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_6_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_7_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_FUNC_ALT0 0x00u

/*! @name PIO1_2 (coord G12), LED_SYS_GREEN
  @{ */
#define BOARD_LED_SYS_GREEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_SYS_GREEN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_LED_SYS_GREEN_PIN 2U    /*!<@brief 1U pin index: 2 */
                                      /* @} */

/*! @name PIO1_3 (coord G13), LED_SYS_RED
  @{ */
#define BOARD_LED_SYS_RED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_SYS_RED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_LED_SYS_RED_PIN 3U    /*!<@brief 1U pin index: 3 */
                                    /* @} */

/*! @name PIO1_14 (coord L7), LED_BAT_GREEN
  @{ */
#define BOARD_LED_BAT_GREEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_BAT_GREEN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_LED_BAT_GREEN_PIN 14U   /*!<@brief 1U pin index: 14 */
                                      /* @} */

/*! @name PIO1_15 (coord B6), LED_BAT_RED
  @{ */
#define BOARD_LED_BAT_RED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_BAT_RED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_LED_BAT_RED_PIN 15U   /*!<@brief 1U pin index: 15 */
                                    /* @} */

/*! @name PIO0_19 (coord E6), LED_BLE_GREEN
  @{ */
#define BOARD_LED_BLE_GREEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_BLE_GREEN_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_LED_BLE_GREEN_PIN 19U   /*!<@brief 0U pin index: 19 */
                                      /* @} */

/*! @name PIO0_20 (coord B12), LED_BLE_RED
  @{ */
#define BOARD_LED_BLE_RED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_BLE_RED_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_LED_BLE_RED_PIN 20U   /*!<@brief 0U pin index: 20 */
                                    /* @} */

/*! @name PIO1_18 (coord G9), KEY_WAKE
  @{ */
#define BOARD_KEY_WAKE_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_KEY_WAKE_PIN 18U /*!<@brief 1U pin index: 18 */
                               /* @} */

/*! @name PIO1_10 (coord J7), PWR_ADC
  @{ */
#define BOARD_PWR_ADC_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_ADC_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_PWR_ADC_PIN 10U   /*!<@brief 1U pin index: 10 */
                                /* @} */

/*! @name PIO0_25 (coord A11), PWR_5V
  @{ */
#define BOARD_PWR_5V_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_5V_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_PWR_5V_PIN 25U   /*!<@brief 0U pin index: 25 */
                               /* @} */

/*! @name PIO0_24 (coord E12), PWR_OFF
  @{ */
#define BOARD_PWR_OFF_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_OFF_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_PWR_OFF_PIN 24U   /*!<@brief 0U pin index: 24 */
                                /* @} */

/*! @name PIO0_17 (coord G3), BAT_STDBY
  @{ */
#define BOARD_BAT_STDBY_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_BAT_STDBY_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_BAT_STDBY_PIN 17U   /*!<@brief 0U pin index: 17 */
                                  /* @} */

/*! @name PIO1_0 (coord E1), BAT_CHRG
  @{ */
#define BOARD_BAT_CHRG_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_BAT_CHRG_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_BAT_CHRG_PIN 0U    /*!<@brief 1U pin index: 0 */
                                 /* @} */

/*! @name PIO1_26 (coord E13), BT_PWR
  @{ */
#define BOARD_BT_PWR_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_BT_PWR_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_BT_PWR_PIN 26U   /*!<@brief 1U pin index: 26 */
                               /* @} */

/*! @name PIO1_30 (coord F9), BT_STATUS
  @{ */
#define BOARD_BT_STATUS_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_BT_STATUS_PIN 30U /*!<@brief 1U pin index: 30 */
                                /* @} */

/*! @name PIO1_27 (coord E8), BT_MODE
  @{ */
#define BOARD_BT_MODE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_BT_MODE_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_BT_MODE_PIN 27U   /*!<@brief 1U pin index: 27 */
                                /* @} */

/*! @name PIO1_25 (coord B8), BT_RST
  @{ */
#define BOARD_BT_RST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_BT_RST_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_BT_RST_PIN 25U   /*!<@brief 1U pin index: 25 */
                               /* @} */

/*! @name PIO0_2 (coord B11), BT_TXD
  @{ */
#define BOARD_BT_TXD_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_BT_TXD_PIN 2U  /*!<@brief 0U pin index: 2 */
                             /* @} */

/*! @name PIO0_3 (coord F8), BT_RXD
  @{ */
#define BOARD_BT_RXD_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_BT_RXD_PIN 3U  /*!<@brief 0U pin index: 3 */
                             /* @} */

/*! @name PIO1_19 (coord H13), PWR_NB
  @{ */
#define BOARD_PWR_NB_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_NB_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_PWR_NB_PIN 19U   /*!<@brief 1U pin index: 19 */
                               /* @} */

/*! @name PIO0_18 (coord H9), NB_RELOAD
  @{ */
#define BOARD_NB_RELOAD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_NB_RELOAD_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_NB_RELOAD_PIN 18U   /*!<@brief 0U pin index: 18 */
                                  /* @} */

/*! @name PIO0_29 (coord H8), NB_NETSTATUS
  @{ */
#define BOARD_NB_NETSTATUS_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_NB_NETSTATUS_PIN 29U /*!<@brief 0U pin index: 29 */
                                   /* @} */

/*! @name PIO1_28 (coord A8), NB_RST
  @{ */
#define BOARD_NB_RST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_NB_RST_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_NB_RST_PIN 28U   /*!<@brief 1U pin index: 28 */
                               /* @} */

/*! @name PIO0_10 (coord F2), ADC_FORMAT
  @{ */
#define BOARD_ADC_FORMAT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_ADC_FORMAT_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_ADC_FORMAT_PIN 10U   /*!<@brief 0U pin index: 10 */
                                   /* @} */

/*! @name PIO0_16 (coord J2), ADC_SYNC
  @{ */
#define BOARD_ADC_SYNC_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_ADC_SYNC_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_ADC_SYNC_PIN 16U   /*!<@brief 0U pin index: 16 */
                                 /* @} */

/*! @name PIO0_7 (coord G5), ADC_MODE
  @{ */
#define BOARD_ADC_MODE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_ADC_MODE_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_ADC_MODE_PIN 7U    /*!<@brief 0U pin index: 7 */
                                 /* @} */

/*! @name PIO0_21 (coord A12), ADC_RDY
  @{ */
#define BOARD_ADC_RDY_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_ADC_RDY_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_ADC_RDY_PIN 21U   /*!<@brief 0U pin index: 21 */
                                /* @} */

/*! @name PIO1_6 (coord H5), PWR_AL
  @{ */
#define BOARD_PWR_CHG_COMPLETE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_CHG_COMPLETE_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_PWR_CHG_COMPLETE_PIN 6U    /*!<@brief 1U pin index: 6 */
                                         /* @} */

/*! @name PIO1_20 (coord C2), PWR_SCL
  @{ */
#define BOARD_PWR_SCL_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_SCL_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_PWR_SCL_PIN 20U   /*!<@brief 1U pin index: 20 */
                                /* @} */

/*! @name PIO1_21 (coord M7), PWR_SDA
  @{ */
#define BOARD_PWR_SDA_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PWR_SDA_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_PWR_SDA_PIN 21U   /*!<@brief 1U pin index: 21 */
                                /* @} */

/*! @name PIO1_7 (coord J5), SENSOR_ST
  @{ */
#define BOARD_SENSOR_ST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_SENSOR_ST_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_SENSOR_ST_PIN 7U    /*!<@brief 1U pin index: 7 */
                                  /* @} */

/*! @name PIO1_1 (coord G11), TEMP_ALT
  @{ */
#define BOARD_TEMP_ALT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_TEMP_ALT_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_TEMP_ALT_PIN 1U    /*!<@brief 1U pin index: 1 */
                                 /* @} */

/*! @name PIO0_14 (coord C13), TMP_SCL
  @{ */
#define BOARD_TMP_SCL_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_TMP_SCL_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_TMP_SCL_PIN 14U   /*!<@brief 0U pin index: 14 */
                                /* @} */

/*! @name PIO0_13 (coord C12), TMP_SDA
  @{ */
#define BOARD_TMP_SDA_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_TMP_SDA_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_TMP_SDA_PIN 13U   /*!<@brief 0U pin index: 13 */
                                /* @} */

/*! @name PIO1_13 (coord B3), FLASH_MOSI
  @{ */
#define BOARD_FLASH_MOSI_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_FLASH_MOSI_PIN 13U /*!<@brief 1U pin index: 13 */
                                 /* @} */

/*! @name PIO1_16 (coord C7), FLASH_MISO
  @{ */
#define BOARD_FLASH_MISO_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_FLASH_MISO_PIN 16U /*!<@brief 1U pin index: 16 */
                                 /* @} */

/*! @name PIO1_12 (coord F12), FLASH_SCK
  @{ */
#define BOARD_FLASH_SCK_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_FLASH_SCK_PIN 12U /*!<@brief 1U pin index: 12 */
                                /* @} */

/*! @name PIO0_31 (coord L1), FLASH_RESET
  @{ */
#define BOARD_FLASH_RESET_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_FLASH_RESET_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_FLASH_RESET_PIN 31U   /*!<@brief 0U pin index: 31 */
                                    /* @} */

/*! @name PIO1_17 (coord J9), FLASH_WP
  @{ */
#define BOARD_FLASH_WP_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_FLASH_WP_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_FLASH_WP_PIN 17U   /*!<@brief 1U pin index: 17 */
                                 /* @} */

/*! @name PIO0_4 (coord E7), WIFI_RTS
  @{ */
#define BOARD_WIFI_RTS_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_WIFI_RTS_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_WIFI_RTS_PIN 4U    /*!<@brief 0U pin index: 4 */
                                 /* @} */

/*! @name PIO0_30 (coord E5), ADC_MISO
  @{ */
#define BOARD_ADC_MISO_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_ADC_MISO_PIN 30U /*!<@brief 0U pin index: 30 */
                               /* @} */

/*! @name PIO0_28 (coord F13), ADC_SPI_SCK
  @{ */
#define BOARD_ADC_SPI_SCK_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_ADC_SPI_SCK_PIN 28U /*!<@brief 0U pin index: 28 */
                                  /* @} */

/*! @name PIO0_27 (coord N2), NB_RXD
  @{ */
#define BOARD_NB_RXD_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_NB_RXD_PIN 27U /*!<@brief 0U pin index: 27 */
                             /* @} */

/*! @name PIO0_26 (coord H12), NB_TXD
  @{ */
#define BOARD_NB_TXD_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_NB_TXD_PIN 26U /*!<@brief 0U pin index: 26 */
                             /* @} */

/*! @name PIO0_15 (coord L2), FLASH_CS
  @{ */
#define BOARD_FLASH_CS_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_FLASH_CS_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_FLASH_CS_PIN 15U   /*!<@brief 0U pin index: 15 */
                                 /* @} */

/*! @name PIO1_4 (coord B2), FLT_CLK
  @{ */
#define BOARD_FLT_CLK_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_FLT_CLK_PIN 4U  /*!<@brief 1U pin index: 4 */
                              /* @} */

/*! @name PIO0_0 (coord L12), ADC_CLK
  @{ */
#define BOARD_ADC_CLK_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_ADC_CLK_PIN 0U  /*!<@brief 0U pin index: 0 */
                              /* @} */

/*! @name PIO0_1 (coord F5), SPD_FREQ_CAP
  @{ */
#define BOARD_SPD_FREQ_CAP_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_SPD_FREQ_CAP_PIN 1U  /*!<@brief 0U pin index: 1 */
                                   /* @} */

/*! @name PIO1_9 (coord C1), selFREQ
  @{ */
#define BOARD_selFREQ_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_selFREQ_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_selFREQ_PIN 9U    /*!<@brief 1U pin index: 9 */
                                /* @} */

/*! @name PIO0_5 (coord A7), WIFI_CTS
  @{ */
#define BOARD_WIFI_CTS_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_WIFI_CTS_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_WIFI_CTS_PIN 5U    /*!<@brief 0U pin index: 5 */
                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
